# Rust formatting configuration for PSOC project

# Basic formatting (stable features only)
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
edition = "2021"

# Import organization (stable features)
reorder_imports = true
reorder_modules = true

# Code style (stable features)
remove_nested_parens = true

# Misc (stable features)
use_field_init_shorthand = true
force_explicit_abi = true

# Note: Many formatting options require nightly Rust
# For production use, we stick to stable features only
# To use advanced formatting, install nightly and add:
# unstable_features = true
