# Clippy configuration for PSOC project

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Documentation requirements
missing-docs-in-crate-items = true

# Avoid false positives for large types
type-complexity-threshold = 250

# Allow some common patterns
avoid-breaking-exported-api = false

# Enum variant name threshold
enum-variant-name-threshold = 3

# Single char binding names to avoid
single-char-binding-names-threshold = 4

# Trivial copy pass by value threshold
trivial-copy-size-limit = 64

# Too many arguments threshold
too-many-arguments-threshold = 7

# Too many lines threshold
too-many-lines-threshold = 100

# Verbose bit mask threshold
verbose-bit-mask-threshold = 1
